
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"



[build]
publish = "public"
command = "hugo --gc --minify --theme book"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --theme book --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --theme book --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.70.0"

[context.branch-deploy]
command = "hugo --gc --minify --theme book -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.70.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

